export type Terrain = 'trail' | 'road' | 'mixed'
export type Category = 'road-5k' | 'road-8k' | 'trail-5k' | 'trail-8k' | 'social-long-run'

export interface Route {
  slug: string
  name: string
  file: string
  category: Category
  terrain: Terrain
  distance_km: number
  elevation_m: number
  center: [number, number]
  description?: string
}

export const ROUTES: Route[] = [
  { slug: 'road-5k--ainsworth-turks-bolton-rd', name: 'Ainsworth, Turks & Bolton Rd', file: 'road-5k--ainsworth-turks-bolton-rd.gpx', category: 'road-5k', terrain: 'road', distance_km: 5.5, elevation_m: 48, center: [53.56453, -2.33928] },
  { slug: 'road-5k--banana-path-one-loop', name: 'Banana Path (One Loop)', file: 'road-5k--banana-path-one-loop.gpx', category: 'road-5k', terrain: 'road', distance_km: 5.1, elevation_m: 47, center: [53.56508, -2.33544] },
  { slug: 'road-5k--christmas-route', name: 'Christmas Route', file: 'road-5k--christmas-route.gpx', category: 'road-5k', terrain: 'road', distance_km: 7.3, elevation_m: 94, center: [53.54911, -2.31355] },
  { slug: 'road-5k--church-st-eton-hill-spring-lane-asda', name: 'Church St, Eton Hill & Spring Lane', file: 'road-5k--church-st-eton-hill-spring-lane-asda.gpx', category: 'road-5k', terrain: 'road', distance_km: 5.4, elevation_m: 31, center: [53.5647, -2.32225] },
  { slug: 'road-5k--eton-hill-road-bury-road-spring-lane', name: 'Eton Hill Road & Bury Road', file: 'road-5k--eton-hill-road-bury-road-spring-lane.gpx', category: 'road-5k', terrain: 'road', distance_km: 4.9, elevation_m: 30, center: [53.5647, -2.32009] },
  { slug: 'road-5k--oab-to-bury', name: 'Outwood to Bury', file: 'road-5k--oab-to-bury.gpx', category: 'road-5k', terrain: 'road', distance_km: 9.3, elevation_m: 44, center: [53.57303, -2.3109] },
  { slug: 'road-5k--oab-to-phillips-park', name: 'Outwood to Phillips Park', file: 'road-5k--oab-to-phillips-park.gpx', category: 'road-5k', terrain: 'road', distance_km: 8.0, elevation_m: 77, center: [53.54818, -2.31212] },
  { slug: 'road-5k--rnr-bnr-higher-lane-stand', name: 'Higher Lane & Stand', file: 'road-5k--rnr-bnr-higher-lane-stand.gpx', category: 'road-5k', terrain: 'road', distance_km: 5.8, elevation_m: 75, center: [53.55267, -2.30988] },
  { slug: 'road-5k--rnr-bnr-pinfold-higher-ringley-stand', name: 'Pinfold, Higher Ringley & Stand', file: 'road-5k--rnr-bnr-pinfold-higher-ringley-stand.gpx', category: 'road-5k', terrain: 'road', distance_km: 6.0, elevation_m: 76, center: [53.55242, -2.30988] },
  { slug: 'road-5k--rnr-bury-nr-higher-ln', name: 'Bury New Road & Higher Lane', file: 'road-5k--rnr-bury-nr-higher-ln.gpx', category: 'road-5k', terrain: 'road', distance_km: 6.3, elevation_m: 71, center: [53.55139, -2.30785] },
  { slug: 'road-5k--rnr-dales-ringley-outwood-sion-oab', name: 'Dales, Ringley & Outwood', file: 'road-5k--rnr-dales-ringley-outwood-sion-oab.gpx', category: 'road-5k', terrain: 'road', distance_km: 8.8, elevation_m: 90, center: [53.55179, -2.32472] },
  { slug: 'road-5k--rnr-ringley-outwood', name: 'Ringley & Outwood', file: 'road-5k--rnr-ringley-outwood.gpx', category: 'road-5k', terrain: 'road', distance_km: 5.6, elevation_m: 73, center: [53.55178, -2.31406] },
  { slug: 'road-8k--3-peaks', name: '3 Peaks', file: 'road-8k--3-peaks.gpx', category: 'road-8k', terrain: 'road', distance_km: 9.9, elevation_m: 174, center: [53.55354, -2.31418] },
  { slug: 'road-8k--banana-path-two-loops', name: 'Banana Path (Two Loops)', file: 'road-8k--banana-path-two-loops.gpx', category: 'road-8k', terrain: 'road', distance_km: 8.0, elevation_m: 71, center: [53.56509, -2.33545] },
  { slug: 'road-8k--dumers-mcr-rd-bury-rd', name: 'Dumers, Manchester Rd & Bury Rd', file: 'road-8k--dumers-mcr-rd-bury-rd.gpx', category: 'road-8k', terrain: 'road', distance_km: 8.5, elevation_m: 47, center: [53.56996, -2.31198] },
  { slug: 'road-8k--oab-to-bury', name: 'Outwood to Bury (Long)', file: 'road-8k--oab-to-bury.gpx', category: 'road-8k', terrain: 'road', distance_km: 9.3, elevation_m: 44, center: [53.57303, -2.3109] },
  { slug: 'road-8k--oab-to-phillips-park', name: 'Outwood to Phillips Park (Long)', file: 'road-8k--oab-to-phillips-park.gpx', category: 'road-8k', terrain: 'road', distance_km: 8.0, elevation_m: 77, center: [53.54818, -2.31212] },
  { slug: 'road-8k--radcliffe-moor-bolton-bury-reverse', name: 'Radcliffe Moor, Bolton & Bury (Reverse)', file: 'road-8k--radcliffe-moor-bolton-bury-reverse.gpx', category: 'road-8k', terrain: 'road', distance_km: 9.0, elevation_m: 78, center: [53.57011, -2.34627] },
  { slug: 'road-8k--radcliffe-moor-bolton-bury', name: 'Radcliffe Moor, Bolton & Bury', file: 'road-8k--radcliffe-moor-bolton-bury.gpx', category: 'road-8k', terrain: 'road', distance_km: 8.8, elevation_m: 73, center: [53.57033, -2.34698] },
  { slug: 'road-8k--rnr-bury-nr-dumers', name: 'Bury New Road & Dumers', file: 'road-8k--rnr-bury-nr-dumers.gpx', category: 'road-8k', terrain: 'road', distance_km: 8.7, elevation_m: 76, center: [53.56245, -2.30363] },
  { slug: 'road-8k--rnr-bury-tesco-ringley-stand', name: 'Bury, Ringley & Stand', file: 'road-8k--rnr-bury-tesco-ringley-stand.gpx', category: 'road-8k', terrain: 'road', distance_km: 8.4, elevation_m: 88, center: [53.54758, -2.30714] },
  { slug: 'road-8k--rnr-dales-ringley-outwood-sion-oab', name: 'Dales, Ringley & Outwood (Long)', file: 'road-8k--rnr-dales-ringley-outwood-sion-oab.gpx', category: 'road-8k', terrain: 'road', distance_km: 8.8, elevation_m: 90, center: [53.55179, -2.32472] },
  { slug: 'road-8k--rnr-rufford-moss-pinfold-ringley-outwood', name: 'Rufford Moss, Pinfold & Ringley', file: 'road-8k--rnr-rufford-moss-pinfold-ringley-outwood.gpx', category: 'road-8k', terrain: 'road', distance_km: 8.6, elevation_m: 101, center: [53.55136, -2.30463] },
  { slug: 'social-long-run--steel-cotton-rail-trail-stage-4-edale-to-hathersage', name: 'Steel & Cotton Trail — Edale to Hathersage', file: 'social-long-run--steel-cotton-rail-trail-stage-4-edale-to-hathersage.gpx', category: 'social-long-run', terrain: 'mixed', distance_km: 19.9, elevation_m: 249, center: [53.35228, -1.73411] },
  { slug: 'social-long-run--steel-cotton-rail-trail-stage-5-hathersage-to-sheffield', name: 'Steel & Cotton Trail — Hathersage to Sheffield', file: 'social-long-run--steel-cotton-rail-trail-stage-5-hathersage-to-sheffield.gpx', category: 'social-long-run', terrain: 'mixed', distance_km: 22.1, elevation_m: 283, center: [53.34131, -1.55814] },
  { slug: 'trail-5k--ainsworth-lowercroft-reservoirs', name: 'Ainsworth & Lowercroft Reservoirs', file: 'trail-5k--ainsworth-lowercroft-reservoirs.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 5.5, elevation_m: 101, center: [53.59342, -2.3521] },
  { slug: 'trail-5k--burrs-tour', name: 'Burrs Tour', file: 'trail-5k--burrs-tour.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 5.6, elevation_m: 95, center: [53.61414, -2.29863] },
  { slug: 'trail-5k--clifton-county-park', name: 'Clifton Country Park', file: 'trail-5k--clifton-county-park.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 5.2, elevation_m: 43, center: [53.53426, -2.34231] },
  { slug: 'trail-5k--crompton-lodges-and-canal', name: 'Crompton Lodges & Canal', file: 'trail-5k--crompton-lodges-and-canal.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 4.6, elevation_m: 67, center: [53.5549, -2.38572] },
  { slug: 'trail-5k--exploring-elton', name: 'Exploring Elton', file: 'trail-5k--exploring-elton.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 5.5, elevation_m: 44, center: [53.58298, -2.3129], description: 'A short climb out of Radcliffe brings you up past Deardens Lodge and along the southwest shore of Elton Reservoir — a lovely stretch of open water that makes the effort worthwhile. From the reservoir the route picks up the Manchester, Bolton & Bury Canal towpath for a flat, easy run back south to the market. Compact, scenic, and a great introduction to the Elton valley.' },
  { slug: 'trail-5k--halloween-run', name: 'Halloween Run', file: 'trail-5k--halloween-run.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 6.1, elevation_m: 39, center: [53.57184, -2.37143] },
  { slug: 'trail-5k--out-and-back-along-the-canal', name: 'Canal Out & Back', file: 'trail-5k--out-and-back-along-the-canal.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 5.2, elevation_m: 22, center: [53.56774, -2.32095] },
  { slug: 'trail-5k--outwood-canal-banana-path', name: 'Outwood, Canal & Banana Path', file: 'trail-5k--outwood-canal-banana-path.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 4.8, elevation_m: 42, center: [53.55801, -2.33476] },
  { slug: 'trail-5k--outwood-king-george-v-playing-fields', name: 'Outwood & King George V Fields', file: 'trail-5k--outwood-king-george-v-playing-fields.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 6.0, elevation_m: 86, center: [53.55424, -2.32136] },
  { slug: 'trail-5k--outwood-oab', name: 'Outwood Out & Back', file: 'trail-5k--outwood-oab.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 9.7, elevation_m: 53, center: [53.54472, -2.32944], description: 'Head out through Outwood Country Park before dropping down to the Manchester, Bolton & Bury Canal towpath. The Outwood Trail and Irwell Sculpture Trail carry you south through Giant\'s Seat Wood and into Clifton Country Park at the far point, surrounded by woodland on both sides. The return mirrors the outward leg — the same views, a steady climb back along the trail, and a quick descent home to the market.' },
  { slug: 'trail-5k--outwood-ringley-lake', name: 'Outwood & Ringley Lake', file: 'trail-5k--outwood-ringley-lake.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 5.1, elevation_m: 62, center: [53.55333, -2.33278] },
  { slug: 'trail-5k--outwood-to-ringley', name: 'Outwood to Ringley', file: 'trail-5k--outwood-to-ringley.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 5.5, elevation_m: 61, center: [53.55331, -2.33705] },
  { slug: 'trail-5k--outwood-to-scout-camp-and-back', name: 'Outwood to Scout Camp & Back', file: 'trail-5k--outwood-to-scout-camp-and-back.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 5.2, elevation_m: 40, center: [53.55083, -2.33553] },
  { slug: 'trail-5k--rnr-chapelfield', name: 'Chapelfield', file: 'trail-5k--rnr-chapelfield.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 5.0, elevation_m: 77, center: [53.55496, -2.31907], description: 'Head out past Coronation and Springwater Parks before the main climb — 50 metres up to the run\'s high point via Nursery Brow, a steady pull that rewards you with open views across the valley. From the top, a sharp descent through Outwood Country Park brings you back down towards town in two stages. Short on distance but with a real climb in the middle — 77 metres of elevation in 5k is a proper workout.' },
  { slug: 'trail-5k--rtr-5k-withins-res-back-via-banana-path', name: 'Withins Reservoir via Banana Path', file: 'trail-5k--rtr-5k-withins-res-back-via-banana-path.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 6.1, elevation_m: 48, center: [53.56784, -2.32727], description: 'A quick climb from Radcliffe Market brings you up to the Manchester, Bolton & Bury Canal, then a gradual rise along the towpath to Withins Reservoir — a peaceful spot at the run\'s high point. The return picks up the Banana Path for a more direct, gentle descent back down to town. Good underfoot throughout and a satisfying loop for 6k.' },
  { slug: 'trail-5k--springwater-new-path', name: 'Springwater (New Path)', file: 'trail-5k--springwater-new-path.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 5.5, elevation_m: 97, center: [53.55778, -2.3117] },
  { slug: 'trail-5k--springwater-park', name: 'Springwater Park', file: 'trail-5k--springwater-park.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 5.5, elevation_m: 84, center: [53.55788, -2.31055] },
  { slug: 'trail-5k--withins-and-elton-back-along-canal', name: 'Withins & Elton, back via Canal', file: 'trail-5k--withins-and-elton-back-along-canal.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 7.0, elevation_m: 43, center: [53.57048, -2.32065] },
  { slug: 'trail-5k--withins-res-back-via-banana-path', name: 'Withins Reservoir & Banana Path', file: 'trail-5k--withins-res-back-via-banana-path.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 6.1, elevation_m: 48, center: [53.56784, -2.32727] },
  { slug: 'trail-8k--ainsworth-bradley-fold-canal', name: 'Ainsworth, Bradley Fold & Canal', file: 'trail-8k--ainsworth-bradley-fold-canal.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 9.0, elevation_m: 58, center: [53.56532, -2.34778] },
  { slug: 'trail-8k--ainsworth-lowercroft-reservoirs', name: 'Ainsworth & Lowercroft Reservoirs (Long)', file: 'trail-8k--ainsworth-lowercroft-reservoirs.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 9.0, elevation_m: 167, center: [53.59352, -2.3418] },
  { slug: 'trail-8k--along-the-canal-and-around-elton', name: 'Canal & Around Elton', file: 'trail-8k--along-the-canal-and-around-elton.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 8.3, elevation_m: 53, center: [53.57139, -2.32075] },
  { slug: 'trail-8k--along-the-canal-to-elton-res', name: 'Canal to Elton Reservoir', file: 'trail-8k--along-the-canal-to-elton-res.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 8.8, elevation_m: 39, center: [53.57047, -2.32525] },
  { slug: 'trail-8k--burrs-to-summerseat-loop', name: 'Burrs to Summerseat Loop', file: 'trail-8k--burrs-to-summerseat-loop.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 9.1, elevation_m: 115, center: [53.61542, -2.31794] },
  { slug: 'trail-8k--canal-around-elton-and-back-via-banana-path', name: 'Canal, Elton & Banana Path', file: 'trail-8k--canal-around-elton-and-back-via-banana-path.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 9.1, elevation_m: 63, center: [53.57243, -2.32652], description: 'Climb up to the canal from Radcliffe Market and follow the towpath north with the reservoir stretching out ahead. Elton Reservoir appears around halfway — loop the southern shore before picking up the Banana Path for the return leg. A route of two halves: open canal and reservoir on the way out, woodland tracks back — mostly gradual with no sharp climbs.' },
  { slug: 'trail-8k--canal-elton-woos-daisyfield', name: 'Canal, Elton & Daisyfield', file: 'trail-8k--canal-elton-woos-daisyfield.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 8.8, elevation_m: 41, center: [53.57382, -2.32052] },
  { slug: 'trail-8k--canal-out-road-back', name: 'Canal Out, Road Back', file: 'trail-8k--canal-out-road-back.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 8.3, elevation_m: 55, center: [53.55934, -2.35008] },
  { slug: 'trail-8k--chapelfield-ringley-old-hall-outwood', name: 'Chapelfield, Ringley Old Hall & Outwood', file: 'trail-8k--chapelfield-ringley-old-hall-outwood.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 8.9, elevation_m: 98, center: [53.54511, -2.32729], description: 'The route earns its metres early — a sustained 61-metre climb in the first two kilometres takes you up through Chapelfield and past Ringley Old Hall before a steep descent into the woodland basin below. From there it threads through Snape Hill Wood, North Wood, and Clifton Country Park before rising again along the Irwell Sculpture Trail and Outwood Trail. The final kilometres follow the Manchester, Bolton & Bury Canal back home — a long, varied loop with nearly 100 metres of climbing and a proper mix of trail, wood, and towpath.' },
  { slug: 'trail-8k--clifton-country-park', name: 'Clifton Country Park (Long)', file: 'trail-8k--clifton-country-park.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 8.4, elevation_m: 65, center: [53.53348, -2.33629] },
  { slug: 'trail-8k--crompton-lodges-and-canal', name: 'Crompton Lodges & Canal (Long)', file: 'trail-8k--crompton-lodges-and-canal.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 8.2, elevation_m: 105, center: [53.55653, -2.38335] },
  { slug: 'trail-8k--halloween-run', name: 'Halloween Run (Long)', file: 'trail-8k--halloween-run.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 6.1, elevation_m: 39, center: [53.57184, -2.37143] },
  { slug: 'trail-8k--kirkless-trail', name: 'Kirklees Trail', file: 'trail-8k--kirkless-trail.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 9.0, elevation_m: 89, center: [53.59662, -2.31776], description: 'A classic on-tour route starting near Bury, heading north on the Kirklees Trail before dropping briefly into a sustained climb through the Elton valley. The route passes through Elton Vale at the far point and loops back south — 89 metres of elevation across 9k makes this one of the more demanding options, with the reward being some of the best trail running in the area. Expect good ground underfoot and open views as you gain height.' },
  { slug: 'trail-8k--outwood-giants-seat-snape', name: "Outwood, Giant's Seat & Snape", file: 'trail-8k--outwood-giants-seat-snape.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 10.1, elevation_m: 146, center: [53.54614, -2.32899] },
  { slug: 'trail-8k--outwood-hurst-wood-golf-course-chapelfield', name: 'Outwood, Hurst Wood & Chapelfield', file: 'trail-8k--outwood-hurst-wood-golf-course-chapelfield.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 7.7, elevation_m: 89, center: [53.54805, -2.32683] },
  { slug: 'trail-8k--outwood-oab', name: 'Outwood Out & Back (Long)', file: 'trail-8k--outwood-oab.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 9.7, elevation_m: 53, center: [53.54472, -2.32944], description: 'Head out through Outwood Country Park before dropping down to the Manchester, Bolton & Bury Canal towpath. The Outwood Trail and Irwell Sculpture Trail carry you south through Giant\'s Seat Wood and into Clifton Country Park at the far point, surrounded by woodland on both sides. The return mirrors the outward leg — the same views, a steady climb back along the trail, and a quick descent home to the market. An out-and-back that earns its distance.' },
  { slug: 'trail-8k--outwood-ringley-canal-diversion', name: 'Outwood, Ringley & Canal (Diversion)', file: 'trail-8k--outwood-ringley-canal-diversion.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 9.5, elevation_m: 93, center: [53.55048, -2.35156] },
  { slug: 'trail-8k--outwood-ringley-canal', name: 'Outwood, Ringley & Canal', file: 'trail-8k--outwood-ringley-canal.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 9.2, elevation_m: 81, center: [53.55046, -2.35154] },
  { slug: 'trail-8k--stand-snape-outwood', name: 'Stand, Snape & Outwood', file: 'trail-8k--stand-snape-outwood.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 8.3, elevation_m: 106, center: [53.54632, -2.32817] },
  { slug: 'trail-8k--withins-and-elton-back-via-canal', name: 'Withins & Elton, back via Canal (Long)', file: 'trail-8k--withins-and-elton-back-via-canal.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 8.7, elevation_m: 47, center: [53.5737, -2.3193] },
]

export const TERRAIN_LABELS: Record<string, string> = {
  trail: 'Trail', road: 'Road', mixed: 'Mixed',
}
