export type Terrain = 'trail' | 'road' | 'mixed'
export type Category = 'road-5k' | 'road-8k' | 'trail-5k' | 'trail-8k' | 'social-long-run'

export interface Route {
  slug: string
  name: string
  file: string
  category: Category
  terrain: Terrain
  distance_km: number
  elevation_m: number
  center: [number, number]
  description?: string
}

export const ROUTES: Route[] = [
  { slug: 'road-5k--ainsworth-turks-bolton-rd', name: 'Ainsworth, Turks & Bolton Rd', file: 'road-5k--ainsworth-turks-bolton-rd.gpx', category: 'road-5k', terrain: 'road', distance_km: 5.5, elevation_m: 48, center: [53.56453, -2.33928] , description: 'From the market the route heads out along Blackburn Street and up Ainsworth Road with a gentle climb through the first two kilometres, before Turks Road loops you back and the Manchester, Bolton & Bury Canal towpath carries you home on a flat finish. A steady, well-surfaced route with one modest climb and a pleasant stretch along the water.'},
  { slug: 'road-5k--banana-path-one-loop', name: 'Banana Path (One Loop)', file: 'road-5k--banana-path-one-loop.gpx', category: 'road-5k', terrain: 'road', distance_km: 5.1, elevation_m: 47, center: [53.56508, -2.33544] , description: 'Head out from the market and up over the canal onto the Banana Path — the tarmac track running above the water between Radcliffe and Ainsworth. One full loop of the path and back brings you just over 5k with a single steady climb and an easy drop back to the towpath. A favourite with regulars for its consistent surface and simple navigation.'},
  { slug: 'road-5k--christmas-route', name: 'Christmas Route', file: 'road-5k--christmas-route.gpx', category: 'road-5k', terrain: 'road', distance_km: 7.3, elevation_m: 94, center: [53.54911, -2.31355] , description: 'The Christmas version of the classic hill loop — from the market it\'s straight into a 64-metre climb via Radcliffe New Road and Dales Lane, passing through Coronation and Springwater Parks on the way up. From the high point the route descends back toward town, finishing at a shade under 7.5k. More of a seasonal extended outing than a standard club night.'},
  { slug: 'road-5k--church-st-eton-hill-spring-lane-asda', name: 'Church St, Eton Hill & Spring Lane', file: 'road-5k--church-st-eton-hill-spring-lane-asda.gpx', category: 'road-5k', terrain: 'road', distance_km: 5.4, elevation_m: 31, center: [53.5647, -2.32225] , description: 'A largely flat route along Church Street and Eton Hill Road before Spring Lane picks up the Manchester, Bolton & Bury Canal towpath for the return. Just 31 metres of elevation across 5.4k and mostly well-surfaced paths throughout — a good option on darker evenings when reliable underfoot matters.'},
  { slug: 'road-5k--eton-hill-road-bury-road-spring-lane', name: 'Eton Hill Road & Bury Road', file: 'road-5k--eton-hill-road-bury-road-spring-lane.gpx', category: 'road-5k', terrain: 'road', distance_km: 4.9, elevation_m: 30, center: [53.5647, -2.32009] , description: 'Keeps to Eton Hill Road and Bury Road before catching the canal towpath home. Nearly flat at 30 metres of gain across under 5k — ideal when you want predictable ground for pace work or an easier session.'},
  { slug: 'road-5k--oab-to-bury', name: 'Outwood to Bury', file: 'road-5k--oab-to-bury.gpx', category: 'road-5k', terrain: 'road', distance_km: 9.3, elevation_m: 44, center: [53.57303, -2.3109] , description: 'A long, flat run along the Manchester, Bolton & Bury Canal and Riverside walk into Bury, passing Festival Gardens before the far point near Starkies Wood and Redvales Playing Fields. At 44 metres of elevation across 9.3k it\'s one of the most runnable routes in the programme — straightforward navigation and easy going all the way.'},
  { slug: 'road-5k--oab-to-phillips-park', name: 'Outwood to Phillips Park', file: 'road-5k--oab-to-phillips-park.gpx', category: 'road-5k', terrain: 'road', distance_km: 8.0, elevation_m: 77, center: [53.54818, -2.31212] , description: 'An immediate 55-metre climb in the opening two kilometres takes you up through Coronation and Springwater Parks, then the route descends south to Philips Park and North Wood at the far point. The return retraces the same ground — the climb comes again on the way home, so pace the first hill accordingly.'},
  { slug: 'road-5k--rnr-bnr-higher-lane-stand', name: 'Higher Lane & Stand', file: 'road-5k--rnr-bnr-higher-lane-stand.gpx', category: 'road-5k', terrain: 'road', distance_km: 5.8, elevation_m: 75, center: [53.55267, -2.30988] , description: 'From the market it\'s straight into the main climb — 42 metres up through Coronation and Springwater Parks in the first 1.8k before levelling out across Higher Lane toward Stand. The descent back is gradual and the opening hill is well worth the effort.'},
  { slug: 'road-5k--rnr-bnr-pinfold-higher-ringley-stand', name: 'Pinfold, Higher Ringley & Stand', file: 'road-5k--rnr-bnr-pinfold-higher-ringley-stand.gpx', category: 'road-5k', terrain: 'road', distance_km: 6.0, elevation_m: 76, center: [53.55242, -2.30988] , description: 'Shares the same 43-metre opening climb through Coronation and Springwater Parks as the Higher Lane route but continues out through Pinfold Lane and across to Higher Ringley before swinging back via Stand and Hamilton Road Park. A slightly longer take on the classic hill start.'},
  { slug: 'road-5k--rnr-bury-nr-higher-ln', name: 'Bury New Road & Higher Lane', file: 'road-5k--rnr-bury-nr-higher-ln.gpx', category: 'road-5k', terrain: 'road', distance_km: 6.3, elevation_m: 71, center: [53.55139, -2.30785] , description: 'Straight into the opening climb along Bury New Road — 43 metres up through Coronation and Springwater Parks in the first 1.8k. Once you\'ve crested, Higher Lane carries you back to town on a welcome gradual descent. The climb is concentrated and short; the rest of the route is an easy recovery.'},
  { slug: 'road-5k--rnr-dales-ringley-outwood-sion-oab', name: 'Dales, Ringley & Outwood', file: 'road-5k--rnr-dales-ringley-outwood-sion-oab.gpx', category: 'road-5k', terrain: 'road', distance_km: 8.8, elevation_m: 90, center: [53.55179, -2.32472] , description: 'A longer road loop that earns its distance — 64 metres of climbing through Coronation and Springwater Parks in the first three kilometres before opening out through Dales Lane and Ringley to Outwood Country Park. The Manchester, Bolton & Bury Canal brings you home past Nickerhole Clough on a flat finish.'},
  { slug: 'road-5k--rnr-ringley-outwood', name: 'Ringley & Outwood', file: 'road-5k--rnr-ringley-outwood.gpx', category: 'road-5k', terrain: 'road', distance_km: 5.6, elevation_m: 73, center: [53.55178, -2.31406] , description: 'One of the more demanding 5k-group options — 66 metres up through Coronation and Springwater Parks in the opening 2.8k before swinging out through Ringley to Outwood Country Park. A short route that packs a real climb, with the descent back to the market taking care of itself.'},
  { slug: 'road-8k--3-peaks', name: '3 Peaks', file: 'road-8k--3-peaks.gpx', category: 'road-8k', terrain: 'road', distance_km: 9.9, elevation_m: 174, center: [53.55354, -2.31418] , description: 'Named for good reason — three separate climbs add up to 174 metres of elevation across 9.9k, with the biggest ascent (65 metres) coming between kilometres 3 and 5 through Outwood Country Park. The route finishes back through Coronation and Springwater Parks with the final climb still to come. One of the harder road options in the programme.'},
  { slug: 'road-8k--banana-path-two-loops', name: 'Banana Path (Two Loops)', file: 'road-8k--banana-path-two-loops.gpx', category: 'road-8k', terrain: 'road', distance_km: 8.0, elevation_m: 71, center: [53.56509, -2.33545] , description: 'Two full loops of the Banana Path above the canal, linked by the Coney Green South Footpath and the towpath itself. The 21-metre climb is gentle and repeated, making this a rhythmic route well-suited to tempo running — consistent underfoot and easy to navigate even on darker evenings.'},
  { slug: 'road-8k--dumers-mcr-rd-bury-rd', name: 'Dumers, Manchester Rd & Bury Rd', file: 'road-8k--dumers-mcr-rd-bury-rd.gpx', category: 'road-8k', terrain: 'road', distance_km: 8.5, elevation_m: 47, center: [53.56996, -2.31198] , description: 'One of the flattest options in the programme — just 47 metres of elevation across 8.5k along Manchester Road and Bury Road, looping back past Starkies Wood and Redvales Playing Fields before finishing along the canal. Smooth surfaces throughout and straightforward going the whole way.'},
  { slug: 'road-8k--oab-to-bury', name: 'Outwood to Bury (Long)', file: 'road-8k--oab-to-bury.gpx', category: 'road-8k', terrain: 'road', distance_km: 9.3, elevation_m: 44, center: [53.57303, -2.3109] , description: 'A long, flat run along the Manchester, Bolton & Bury Canal and Riverside walk to Bury, passing Festival Gardens and Redvales Playing Fields on the way. At 44 metres of elevation across 9.3k it\'s one of the most runnable options in the programme — ideal for pace work or recovery miles on predictable ground.'},
  { slug: 'road-8k--oab-to-phillips-park', name: 'Outwood to Phillips Park (Long)', file: 'road-8k--oab-to-phillips-park.gpx', category: 'road-8k', terrain: 'road', distance_km: 8.0, elevation_m: 77, center: [53.54818, -2.31212] , description: 'The opening two kilometres climb 55 metres through Coronation and Springwater Parks before the route descends south to Philips Park and North Wood at the far point. The return retraces the same ground — the climb comes again at the finish, so pace the first ascent well.'},
  { slug: 'road-8k--radcliffe-moor-bolton-bury-reverse', name: 'Radcliffe Moor, Bolton & Bury (Reverse)', file: 'road-8k--radcliffe-moor-bolton-bury-reverse.gpx', category: 'road-8k', terrain: 'road', distance_km: 9.0, elevation_m: 78, center: [53.57011, -2.34627] , description: 'The Radcliffe Moor loop run anti-clockwise — heading north first before the main 49-metre climb arrives between 0.5 and 3.8k while the legs are still fresh. The Manchester, Bolton & Bury Canal features at both ends of the loop, giving flat running to open and close the session.'},
  { slug: 'road-8k--radcliffe-moor-bolton-bury', name: 'Radcliffe Moor, Bolton & Bury', file: 'road-8k--radcliffe-moor-bolton-bury.gpx', category: 'road-8k', terrain: 'road', distance_km: 8.8, elevation_m: 73, center: [53.57033, -2.34698] , description: 'A classic loop along Radcliffe Moor Road before swinging north through Bolton Road and back via Bury Road and the Manchester, Bolton & Bury Canal. The main 28-metre climb comes mid-run between kilometres 3 and 5 — well-timed for when the legs are properly warmed up — with a flat canal finish back to the market.'},
  { slug: 'road-8k--rnr-bury-nr-dumers', name: 'Bury New Road & Dumers', file: 'road-8k--rnr-bury-nr-dumers.gpx', category: 'road-8k', terrain: 'road', distance_km: 8.7, elevation_m: 76, center: [53.56245, -2.30363] , description: 'The 43-metre opening climb through Coronation and Springwater Parks, then down and out along Bury New Road via Whitefield Park, picking up the Manchester, Bolton & Bury Canal towpath for a flat return. Solid 8k structure — climb to start, canal to finish.'},
  { slug: 'road-8k--rnr-bury-tesco-ringley-stand', name: 'Bury, Ringley & Stand', file: 'road-8k--rnr-bury-tesco-ringley-stand.gpx', category: 'road-8k', terrain: 'road', distance_km: 8.4, elevation_m: 88, center: [53.54758, -2.30714] , description: 'The customary 43-metre opening climb through Coronation and Springwater Parks before pushing further out via Bury Road to Ringley and Stand, crossing the Prestwich Footbridge mid-route. At 88 metres of total elevation across 8.4k this is one of the hillier 8k options in the programme.'},
  { slug: 'road-8k--rnr-dales-ringley-outwood-sion-oab', name: 'Dales, Ringley & Outwood (Long)', file: 'road-8k--rnr-dales-ringley-outwood-sion-oab.gpx', category: 'road-8k', terrain: 'road', distance_km: 8.8, elevation_m: 90, center: [53.55179, -2.32472] , description: 'The 8k version of the Dales loop — 90 metres of climbing through Coronation and Springwater Parks early on, then out through Dales Lane and Ringley to Outwood Country Park. The Manchester, Bolton & Bury Canal provides a flat finish home, with Nickerhole Clough passed along the way.'},
  { slug: 'road-8k--rnr-rufford-moss-pinfold-ringley-outwood', name: 'Rufford Moss, Pinfold & Ringley', file: 'road-8k--rnr-rufford-moss-pinfold-ringley-outwood.gpx', category: 'road-8k', terrain: 'road', distance_km: 8.6, elevation_m: 101, center: [53.55136, -2.30463] , description: 'Over 100 metres of elevation across 8.6k — starting with the 43-metre climb through Coronation and Springwater Parks before extending out through Rufford Moss, Pinfold Lane, and Ringley to Outwood Country Park. The sustained distance through Pinfold and Ringley makes this one of the more demanding road 8k options.'},
  { slug: 'social-long-run--burrs-summerseat-loop', name: 'Burrs & Summerseat Loop', file: 'social-long-run--burrs-summerseat-loop.gpx', category: 'social-long-run', terrain: 'mixed', distance_km: 9.1, elevation_m: 115, center: [53.61599, -2.31784], description: 'Starting from Burrs Country Park, the route climbs steadily north through Brandlesholme and Elton across the first 4k before reaching Summerseat village via Higher Summerseat and Railway Street. The return follows Wood Road Lane back through the rolling ground south of the Irwell Valley, with the finish dropping back into the park. A varied 9k with 115 metres of gain — good underfoot in places but expect some mixed surfaces throughout.' },
  { slug: 'social-long-run--steel-cotton-rail-trail-stage-4-edale-to-hathersage', name: 'Steel & Cotton Trail — Edale to Hathersage', file: 'social-long-run--steel-cotton-rail-trail-stage-4-edale-to-hathersage.gpx', category: 'social-long-run', terrain: 'mixed', distance_km: 19.9, elevation_m: 249, center: [53.35228, -1.73411] , description: 'Stage 4 of the Steel & Cotton Rail Trail, running south from Edale through the Hope Valley to Hathersage. The route crosses open moorland before a sustained descent through Backside Wood to the valley floor, then rolls through the latter miles toward the finish. At 20k with 249 metres of climbing this is a proper long run — point-to-point from one rail station to the next.'},
  { slug: 'social-long-run--steel-cotton-rail-trail-stage-5-hathersage-to-sheffield', name: 'Steel & Cotton Trail — Hathersage to Sheffield', file: 'social-long-run--steel-cotton-rail-trail-stage-5-hathersage-to-sheffield.gpx', category: 'social-long-run', terrain: 'mixed', distance_km: 22.1, elevation_m: 283, center: [53.34131, -1.55814] , description: 'Stage 5 of the Steel & Cotton Rail Trail and the biggest day in the social run calendar — 22k with 283 metres of elevation and a 203-metre climb through Padley Gorge between kilometres 3.5 and 8. Beyond the gorge the route descends through Ecclesall Woods, Millhouses Park, and Hutcliffe Wood into Sheffield along the Sheaf valley. A serious undertaking from start to finish.'},
  { slug: 'trail-5k--ainsworth-lowercroft-reservoirs', name: 'Ainsworth & Lowercroft Reservoirs', file: 'trail-5k--ainsworth-lowercroft-reservoirs.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 5.5, elevation_m: 101, center: [53.59342, -2.3521] , description: 'A trip to the Lowercroft Reservoirs above Ainsworth, passing both Top and Middle Lowercroft on a loop of paths above the valley. The terrain rolls throughout with 101 metres of elevation across 5.5k — surprisingly hilly for a 5k trail run, with open reservoir views as the reward for the effort.'},
  { slug: 'trail-5k--burrs-tour', name: 'Burrs Tour', file: 'trail-5k--burrs-tour.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 5.6, elevation_m: 95, center: [53.61414, -2.29863] , description: 'An on-tour run to Burrs Country Park on the Irwell, beginning with a sustained 61-metre climb in the opening 3.8k before dropping into the park and through Seedfield Wood beyond. With 95 metres of elevation across 5.6k this is one of the more demanding 5k trail options in the programme.'},
  { slug: 'trail-5k--clifton-county-park', name: 'Clifton Country Park', file: 'trail-5k--clifton-county-park.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 5.2, elevation_m: 43, center: [53.53426, -2.34231] , description: 'A circuit of Clifton Country Park following the Kingfisher Trail through Giant\'s Seat Wood and past Clifton Marina, with a stretch along the abandoned Fletcher\'s Canal towpath adding character underfoot. Relatively flat at 43 metres over 5.2k — a pleasant, well-signed woodland run.'},
  { slug: 'trail-5k--crompton-lodges-and-canal', name: 'Crompton Lodges & Canal', file: 'trail-5k--crompton-lodges-and-canal.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 4.6, elevation_m: 67, center: [53.5549, -2.38572] , description: 'An on-tour route through Moses Gate Country Park and along the Manchester, Bolton & Bury Canal, finishing at the Nob End SSSI — a botanical site formed from industrial spoil that now supports rare wildflower meadows. Compact at under 5k but 67 metres of elevation packed in throughout.'},
  { slug: 'trail-5k--exploring-elton', name: 'Exploring Elton', file: 'trail-5k--exploring-elton.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 5.5, elevation_m: 44, center: [53.58298, -2.3129], description: 'A short climb out of Radcliffe brings you up past Deardens Lodge and along the southwest shore of Elton Reservoir — a lovely stretch of open water that makes the effort worthwhile. From the reservoir the route picks up the Manchester, Bolton & Bury Canal towpath for a flat, easy run back south to the market. Compact, scenic, and a great introduction to the Elton valley.' },
  { slug: 'trail-5k--halloween-run', name: 'Halloween Run', file: 'trail-5k--halloween-run.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 6.1, elevation_m: 39, center: [53.57184, -2.37143] , description: 'The club\'s annual Halloween outing — flat and fast at 39 metres of elevation across 6k. Fancy dress very much encouraged.'},
  { slug: 'trail-5k--out-and-back-along-the-canal', name: 'Canal Out & Back', file: 'trail-5k--out-and-back-along-the-canal.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 5.2, elevation_m: 22, center: [53.56774, -2.32095] , description: 'About as simple as it gets — out along the Manchester, Bolton & Bury Canal towpath and back. Just 22 metres of elevation across 5.2k, with the only gradient being the short rise from the market at the start. A reliable option for easy miles or for newer runners getting comfortable with the group.'},
  { slug: 'trail-5k--outwood-canal-banana-path', name: 'Outwood, Canal & Banana Path', file: 'trail-5k--outwood-canal-banana-path.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 4.8, elevation_m: 42, center: [53.55801, -2.33476] , description: 'A compact loop touching the key trail landmarks — up through Outwood Country Park on the Outwood Trail and Irwell Sculpture Trail, past Nickerhole Clough, then back via Cams Lane and the canal towpath. Just under 5k with a modest 21-metre opening climb and solid ground throughout.'},
  { slug: 'trail-5k--outwood-king-george-v-playing-fields', name: 'Outwood & King George V Fields', file: 'trail-5k--outwood-king-george-v-playing-fields.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 6.0, elevation_m: 86, center: [53.55424, -2.32136] , description: 'Heads up Pilkington Way and Dale Street with a 35-metre climb in the opening two kilometres before dropping to the King George V Playing Fields and looping back via Sion Street and the Outwood Trail. At 86 metres of total elevation across 6k this is legitimately hilly for a 5k trail run — the kind of route that builds fitness quickly.'},
  { slug: 'trail-5k--outwood-oab', name: 'Outwood Out & Back', file: 'trail-5k--outwood-oab.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 9.7, elevation_m: 53, center: [53.54472, -2.32944], description: 'Head out through Outwood Country Park before dropping down to the Manchester, Bolton & Bury Canal towpath. The Outwood Trail and Irwell Sculpture Trail carry you south through Giant\'s Seat Wood and into Clifton Country Park at the far point, surrounded by woodland on both sides. The return mirrors the outward leg — the same views, a steady climb back along the trail, and a quick descent home to the market.' },
  { slug: 'trail-5k--outwood-ringley-lake', name: 'Outwood & Ringley Lake', file: 'trail-5k--outwood-ringley-lake.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 5.1, elevation_m: 62, center: [53.55333, -2.33278] , description: 'Climbs steadily through Outwood Country Park on the Outwood Trail and Irwell Sculpture Trail — 39 metres up to the high point — before descending to Ringley Lake via King George V Lodge and the canal towpath. A satisfying short loop with elevation to earn the views and the water for company on the way home.'},
  { slug: 'trail-5k--outwood-to-ringley', name: 'Outwood to Ringley', file: 'trail-5k--outwood-to-ringley.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 5.5, elevation_m: 61, center: [53.55331, -2.33705] , description: 'From the market up Blackburn Street and into Outwood Country Park, following the Outwood Trail and Irwell Sculpture Trail on a 32-metre climb before dropping to Ringley. The canal towpath brings you home — a classic climb-and-towpath structure in just over 5k.'},
  { slug: 'trail-5k--outwood-to-scout-camp-and-back', name: 'Outwood to Scout Camp & Back', file: 'trail-5k--outwood-to-scout-camp-and-back.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 5.2, elevation_m: 40, center: [53.55083, -2.33553] , description: 'Up through Outwood Country Park on the Outwood Trail and Irwell Sculpture Trail with a 31-metre climb in the first two kilometres, through Ringley Wood to the Scout Camp at the far point. The return mirrors the outward leg on familiar ground — a compact, well-structured out-and-back.'},
  { slug: 'trail-5k--rnr-chapelfield', name: 'Chapelfield', file: 'trail-5k--rnr-chapelfield.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 5.0, elevation_m: 77, center: [53.55496, -2.31907], description: 'Head out past Coronation and Springwater Parks before the main climb — 50 metres up to the run\'s high point via Nursery Brow, a steady pull that rewards you with open views across the valley. From the top, a sharp descent through Outwood Country Park brings you back down towards town in two stages. Short on distance but with a real climb in the middle — 77 metres of elevation in 5k is a proper workout.' },
  { slug: 'trail-5k--rtr-5k-withins-res-back-via-banana-path', name: 'Withins Reservoir via Banana Path', file: 'trail-5k--rtr-5k-withins-res-back-via-banana-path.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 6.1, elevation_m: 48, center: [53.56784, -2.32727], description: 'A quick climb from Radcliffe Market brings you up to the Manchester, Bolton & Bury Canal, then a gradual rise along the towpath to Withins Reservoir — a peaceful spot at the run\'s high point. The return picks up the Banana Path for a more direct, gentle descent back down to town. Good underfoot throughout and a satisfying loop for 6k.' },
  { slug: 'trail-5k--springwater-new-path', name: 'Springwater (New Path)', file: 'trail-5k--springwater-new-path.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 5.5, elevation_m: 97, center: [53.55778, -2.3117] , description: 'The newer Springwater variant, using paths through Radcliffe Ees and Dales Avenue before the 43-metre main climb through Coronation and Springwater Parks. At 97 metres of elevation across 5.5k this is the hilliest of the Springwater options — proper hill work in a local park setting.'},
  { slug: 'trail-5k--springwater-park', name: 'Springwater Park', file: 'trail-5k--springwater-park.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 5.5, elevation_m: 84, center: [53.55788, -2.31055] , description: 'The standard Springwater loop — the main 43-metre climb comes between kilometres 2 and 3.8, giving the legs time to warm up before the hardest section. At 84 metres of total elevation across 5.5k it\'s a slightly kinder structure than the steeper Springwater variants, with the hill saved for when you\'re ready for it.'},
  { slug: 'trail-5k--withins-and-elton-back-along-canal', name: 'Withins & Elton, back via Canal', file: 'trail-5k--withins-and-elton-back-along-canal.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 7.0, elevation_m: 43, center: [53.57048, -2.32065] , description: 'Canal towpath north to Withins Reservoir via the Lower Withins path, then continuing to Elton Reservoir before looping back south on the towpath home. At 43 metres across 7k it\'s a long, flat trail run — the two reservoirs give it character and the towpath makes navigation effortless throughout.'},
  { slug: 'trail-5k--withins-res-back-via-banana-path', name: 'Withins Reservoir & Banana Path', file: 'trail-5k--withins-res-back-via-banana-path.gpx', category: 'trail-5k', terrain: 'trail', distance_km: 6.1, elevation_m: 48, center: [53.56784, -2.32727] , description: 'Canal out to Withins Reservoir via the Lower Withins path, then the Banana Path back rather than the towpath — a slightly more varied return option on the same fundamental out-and-back structure. 48 metres of elevation across 6.1k with a gentle rise to the reservoir and an easy descent home.'},
  { slug: 'trail-8k--ainsworth-bradley-fold-canal', name: 'Ainsworth, Bradley Fold & Canal', file: 'trail-8k--ainsworth-bradley-fold-canal.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 9.0, elevation_m: 58, center: [53.56532, -2.34778] , description: 'Heads north from the market along Ainsworth Road and Bradley Fold Road before dropping back via Ladyshore and the Nickerhole Clough path into Outwood Country Park. The Manchester, Bolton & Bury Canal carries you home on a flat final section — 58 metres of elevation across 9k with a gentle early climb and a largely runnable profile.'},
  { slug: 'trail-8k--ainsworth-lowercroft-reservoirs', name: 'Ainsworth & Lowercroft Reservoirs (Long)', file: 'trail-8k--ainsworth-lowercroft-reservoirs.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 9.0, elevation_m: 167, center: [53.59352, -2.3418] , description: 'An extended reservoir tour taking in both Top and Middle Lowercroft before looping through Elton Vale and tackling the main 45-metre climb at the halfway point. At 167 metres across 9k this is one of the hilliest 8k trail options in the programme — rolling and demanding throughout with some of the best open-water scenery on any club route.'},
  { slug: 'trail-8k--along-the-canal-and-around-elton', name: 'Canal & Around Elton', file: 'trail-8k--along-the-canal-and-around-elton.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 8.3, elevation_m: 53, center: [53.57139, -2.32075] , description: 'Canal north to Elton Reservoir, then a full loop using both the northwest and southwest shore paths before returning via the Lower Withins path and past Withins Reservoir. Mostly flat at 53 metres across 8.3k — a generous circuit of open water that takes in two reservoirs in one run.'},
  { slug: 'trail-8k--along-the-canal-to-elton-res', name: 'Canal to Elton Reservoir', file: 'trail-8k--along-the-canal-to-elton-res.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 8.8, elevation_m: 39, center: [53.57047, -2.32525] , description: 'Canal all the way north to Elton Reservoir and back along the towpath — almost completely flat at 39 metres across 8.8k. The reservoir is both the destination and the reward; the towpath makes navigation effortless in both directions.'},
  { slug: 'trail-8k--burrs-to-summerseat-loop', name: 'Burrs to Summerseat Loop', file: 'trail-8k--burrs-to-summerseat-loop.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 9.1, elevation_m: 115, center: [53.61542, -2.31794] , description: 'An on-tour loop from Burrs Country Park to Summerseat and back, with 115 metres of rolling elevation across 9k spread across several smaller climbs along the Irwell valley. Burrs Country Park frames both ends of the route and the river stays close throughout — good trail surfaces and plenty to look at.'},
  { slug: 'trail-8k--canal-around-elton-and-back-via-banana-path', name: 'Canal, Elton & Banana Path', file: 'trail-8k--canal-around-elton-and-back-via-banana-path.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 9.1, elevation_m: 63, center: [53.57243, -2.32652], description: 'Climb up to the canal from Radcliffe Market and follow the towpath north with the reservoir stretching out ahead. Elton Reservoir appears around halfway — loop the southern shore before picking up the Banana Path for the return leg. A route of two halves: open canal and reservoir on the way out, woodland tracks back — mostly gradual with no sharp climbs.' },
  { slug: 'trail-8k--canal-elton-woos-daisyfield', name: 'Canal, Elton & Daisyfield', file: 'trail-8k--canal-elton-woos-daisyfield.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 8.8, elevation_m: 41, center: [53.57382, -2.32052] , description: 'Canal north to Elton Reservoir, then continuing along the Farmer\'s Arms Wharf access track and past the Daisyfield Site of Biological Interest before looping back south on the towpath. At 41 metres across 8.8k it\'s one of the flattest longer trail options — the Daisyfield SBI adds a quieter stretch that few runners find on their own.'},
  { slug: 'trail-8k--canal-out-road-back', name: 'Canal Out, Road Back', file: 'trail-8k--canal-out-road-back.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 8.3, elevation_m: 55, center: [53.55934, -2.35008] , description: 'Canal towpath north to the Ladyshore junction, then a return through Mytham Park and Nickerhole Clough back to Outwood Country Park. Easy going out along the water and more varied on the return — 55 metres of elevation concentrated in the middle section with a flat towpath to start and finish.'},
  { slug: 'trail-8k--chapelfield-ringley-old-hall-outwood', name: 'Chapelfield, Ringley Old Hall & Outwood', file: 'trail-8k--chapelfield-ringley-old-hall-outwood.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 8.9, elevation_m: 98, center: [53.54511, -2.32729], description: 'The route earns its metres early — a sustained 61-metre climb in the first two kilometres takes you up through Chapelfield and past Ringley Old Hall before a steep descent into the woodland basin below. From there it threads through Snape Hill Wood, North Wood, and Clifton Country Park before rising again along the Irwell Sculpture Trail and Outwood Trail. The final kilometres follow the Manchester, Bolton & Bury Canal back home — a long, varied loop with nearly 100 metres of climbing and a proper mix of trail, wood, and towpath.' },
  { slug: 'trail-8k--clifton-country-park', name: 'Clifton Country Park (Long)', file: 'trail-8k--clifton-country-park.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 8.4, elevation_m: 65, center: [53.53348, -2.33629] , description: 'A longer exploration of Clifton Country Park taking in Giant\'s Seat Wood, the Kingfisher Trail, Clifton Marina, the abandoned Fletcher\'s Canal, and Fat Hurst Wood via the Pale Walk. At 65 metres across 8.4k the terrain is gentle throughout — a route for taking in the landscape rather than grinding out climbs.'},
  { slug: 'trail-8k--crompton-lodges-and-canal', name: 'Crompton Lodges & Canal (Long)', file: 'trail-8k--crompton-lodges-and-canal.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 8.2, elevation_m: 105, center: [53.55653, -2.38335] , description: 'The extended Crompton Lodges loop covering more of Moses Gate Country Park and the full canal section past the Nob End SSSI. At 105 metres across 8.2k it carries noticeably more elevation than the shorter variant — the Nob End SSSI is a wildflower reserve that makes the extra miles worthwhile.'},
  { slug: 'trail-8k--halloween-run', name: 'Halloween Run (Long)', file: 'trail-8k--halloween-run.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 6.1, elevation_m: 39, center: [53.57184, -2.37143] , description: 'The 8k group\'s Halloween outing — flat and easy at 39 metres across 6k. Come in costume.'},
  { slug: 'trail-8k--kirkless-trail', name: 'Kirklees Trail', file: 'trail-8k--kirkless-trail.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 9.0, elevation_m: 89, center: [53.59662, -2.31776], description: 'A classic on-tour route starting near Bury, heading north on the Kirklees Trail before dropping briefly into a sustained climb through the Elton valley. The route passes through Elton Vale at the far point and loops back south — 89 metres of elevation across 9k makes this one of the more demanding options, with the reward being some of the best trail running in the area. Expect good ground underfoot and open views as you gain height.' },
  { slug: 'trail-8k--outwood-giants-seat-snape', name: "Outwood, Giant's Seat & Snape", file: 'trail-8k--outwood-giants-seat-snape.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 10.1, elevation_m: 146, center: [53.54614, -2.32899] , description: 'The biggest route in the standard trail 8k programme — 10k with 146 metres of elevation and a 71-metre climb between kilometres 4.5 and 6.5. The route threads through Outwood Country Park, Ringley Wood, and Giant\'s Seat Wood before climbing through Little Hurst Wood, Fat Hurst Wood, and Snape Hill Wood via the Pale Walk and Nursery Brow on the way home.'},
  { slug: 'trail-8k--outwood-hurst-wood-golf-course-chapelfield', name: 'Outwood, Hurst Wood & Chapelfield', file: 'trail-8k--outwood-hurst-wood-golf-course-chapelfield.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 7.7, elevation_m: 89, center: [53.54805, -2.32683] , description: 'Canal towpath to Outwood Country Park, then into the woodland network on the Outwood Trail and Irwell Sculpture Trail — Giant\'s Seat Wood, Pale Walk, Little Hurst Wood, and Clifton Country Park before the 50-metre climb back up through Snape Hill Wood and Nursery Brow. A well-structured 7.7k that packs most of the local woodland into a single loop.'},
  { slug: 'trail-8k--outwood-oab', name: 'Outwood Out & Back (Long)', file: 'trail-8k--outwood-oab.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 9.7, elevation_m: 53, center: [53.54472, -2.32944], description: 'Head out through Outwood Country Park before dropping down to the Manchester, Bolton & Bury Canal towpath. The Outwood Trail and Irwell Sculpture Trail carry you south through Giant\'s Seat Wood and into Clifton Country Park at the far point, surrounded by woodland on both sides. The return mirrors the outward leg — the same views, a steady climb back along the trail, and a quick descent home to the market. An out-and-back that earns its distance.' },
  { slug: 'trail-8k--outwood-ringley-canal-diversion', name: 'Outwood, Ringley & Canal (Diversion)', file: 'trail-8k--outwood-ringley-canal-diversion.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 9.5, elevation_m: 93, center: [53.55048, -2.35156] , description: 'The diversion variant of the Outwood-Ringley loop, extending through Moses Gate Country Park and the Nob End SSSI for additional distance and a different finish. It still opens with the 31-metre climb through Outwood Country Park and Ringley Wood — the divergence comes beyond, adding Ladyshore and Nickerhole Clough on the return.'},
  { slug: 'trail-8k--outwood-ringley-canal', name: 'Outwood, Ringley & Canal', file: 'trail-8k--outwood-ringley-canal.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 9.2, elevation_m: 81, center: [53.55046, -2.35154] , description: 'A 32-metre climb through Outwood Country Park on the Outwood Trail and Irwell Sculpture Trail, then through Ringley Wood and out to Nob End SSSI and Moses Gate Country Park, returning via Ladyshore, Nickerhole Clough, and the canal towpath. A varied 9.2k that covers woodland, nature reserve, and water.'},
  { slug: 'trail-8k--stand-snape-outwood', name: 'Stand, Snape & Outwood', file: 'trail-8k--stand-snape-outwood.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 8.3, elevation_m: 106, center: [53.54632, -2.32817] , description: 'Opens with the hardest challenge in the first 1.5k — 57 metres up toward Stand — before descending into the woodland network via Snape Hill Wood, Fat Hurst Wood, and Little Hurst Wood. Giant\'s Seat Wood and Clifton Country Park form the lowest point before the Irwell Sculpture Trail and Outwood Country Park bring the route back up, with Nickerhole Clough and the canal towpath completing the return. A demanding 8.3k with 106 metres of elevation.'},
  { slug: 'trail-8k--withins-and-elton-back-via-canal', name: 'Withins & Elton, back via Canal (Long)', file: 'trail-8k--withins-and-elton-back-via-canal.gpx', category: 'trail-8k', terrain: 'trail', distance_km: 8.7, elevation_m: 47, center: [53.5737, -2.3193] , description: 'Canal north to Withins Reservoir, then extending past Elton Reservoir and the Daisyfield Site of Biological Interest before returning south on the towpath. At 47 metres across 8.7k it\'s a long, largely flat trail run — the two reservoirs and the Daisyfield SBI give this route more to look at than most.'},
]

export const TERRAIN_LABELS: Record<string, string> = {
  trail: 'Trail', road: 'Road', mixed: 'Mixed',
}
